[package]
name = "trundler"
version = "0.1.0"
edition = "2021"
description = "An unofficial SDK for Shopify's Admin API"
license = "GPL-3.0-or-later"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
